import type { Plugin } from 'vite';
import { readdirSync, statSync, readFileSync, writeFileSync, copyFileSync, existsSync } from 'fs';
import { resolve, join } from 'path';

export function drupalSdcGenerator(options: { src: string }): Plugin {
	let outDir = '';

	return {
		name: 'drupal-sdc-generator',
		configResolved(config) {
			outDir = config.build.outDir;
		},
		closeBundle() {
			const srcPath = resolve(options.src);
			// Ensure we are reading the same src directory
			if (!existsSync(srcPath)) return;

			const items = readdirSync(srcPath);

			for (const item of items) {
				const componentSrcDir = join(srcPath, item);

				if (!statSync(componentSrcDir).isDirectory()) continue;
				if (!existsSync(join(componentSrcDir, 'main.ts'))) continue;

				const componentOutputDir = join(outDir, item);
				// Vite usually creates this directory if entry exists
				if (!existsSync(componentOutputDir)) continue;


				const ymlFileName = `${item}.component.yml`;
				const srcYmlPath = join(componentSrcDir, ymlFileName);
				const distYmlPath = join(componentOutputDir, ymlFileName);

				if (existsSync(srcYmlPath)) {
					copyFileSync(srcYmlPath, distYmlPath);
					console.log(`[drupal-sdc] Copied ${ymlFileName}`);
				} else {
					// Scan output directory for .js and .css files generated by Vite
					const outputFiles = readdirSync(componentOutputDir);
					const jsFiles = outputFiles.filter((f) => f.endsWith('.js'));
					const cssFiles = outputFiles.filter((f) => f.endsWith('.css'));

					let jsSection = '';
					if (jsFiles.length > 0) {
						jsSection = 'js:\n';
						jsFiles.forEach((f) => {
							jsSection += `  ${f}: {}\n`;
						});
					}

					let cssSection = '';
					if (cssFiles.length > 0) {
						cssSection = 'css:\n';
						cssFiles.forEach((f) => {
							cssSection += `  ${f}: {}\n`;
						});
					}

					const defaultYml = `$schema: https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json
name: ${item}

${jsSection}${cssSection}
# props:
#   type: object
#   additionalProperties: false
#   properties: {}
`;
					writeFileSync(distYmlPath, defaultYml);
					console.log(`[drupal-sdc] Generated ${ymlFileName}`);
				}


				const twigFileName = `${item}.twig`;
				const srcTwigPath = join(componentSrcDir, twigFileName);
				const distTwigPath = join(componentOutputDir, twigFileName);

				if (existsSync(srcTwigPath)) {
					copyFileSync(srcTwigPath, distTwigPath);
					console.log(`[drupal-sdc] Copied ${twigFileName}`);
				} else {
					// Find svelte file to extract tag
					const svelteFile = join(componentSrcDir, `${item}.svelte`); // Assumes naming convention
					let tagName = 'div'; // Default
					if (existsSync(svelteFile)) {
						const content = readFileSync(svelteFile, 'utf-8');
						const match = content.match(/<svelte:options\s+customElement="([^"]+)"/);
						if (match && match[1]) {
							tagName = match[1];
						}
					}

					const defaultTwig = `<${tagName} />`;
					writeFileSync(distTwigPath, defaultTwig);
					console.log(`[drupal-sdc] Generated ${twigFileName}`);
				}
			}
		}
	}
}
